url: "https://profilejumper.com"
title: "Profile Jumper!"
url_chrome_store: "https://chrome.google.com/webstore/detail/profile-jumper-jump-betwe/fgjjcaimpepmohgbbeaooecldlknlkef"
url_github: "https://github.com/profile-jumper"
